function y = generateSweep(sampleRate, chirpLength, volume)
    logchirp = dsp.Chirp(...
     'Type', 'Logarithmic', ...
     'SweepDirection', 'Unidirectional', ...
     'TargetFrequency', 20000, ... 
     'InitialFrequency', 20,...
     'TargetTime', chirpLength, ...
     'SweepTime', chirpLength, ...
     'InitialPhase', 0, ...
     'SamplesPerFrame', (sampleRate*chirpLength), ...
     'SampleRate', sampleRate);

    padLength=2000;
    y = logchirp.step;
    y = padarray(y,padLength,0,'pre');
    sweepLength=length(y);
    for i=1:padLength
        y(i,1)=i/padLength;
        y(sweepLength+i,1)= y(sweepLength)-(y(sweepLength)*i/padLength);
    end  
    
    y = y*volume;
end

